apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: db
status:
  loadBalancer: {}
