version: '3'

services:
  erc20detector:
    container_name: erc20detector
    command: sh -c "alembic upgrade head && uvicorn --factory erc20detector.main.web:create_app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: .
    volumes:
      - ./src:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
     - postgres_data:/var/lib/postgresql/data/

volumes:
 postgres_data:
