apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: erc20detector
  name: erc20detector
spec:
  selector:
    app: erc20detector
  ports:
  - name: http
    protocol: TCP
    port: 8000
status:
  loadBalancer: {}
