apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: erc20detector
  name: erc20detector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: erc20detector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: erc20detector
    spec:
      containers:
        - name: erc20detector
          image: kirillstepankov/erc20detector:0.2.0
          command: ["sh", "-c", "uvicorn --factory erc20detector.main.web:create_app --host 0.0.0.0 --port 8000 --reload"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: erc20detector-env
          resources: {}
      restartPolicy: Always
status: {}
