"""initial

Revision ID: 19e7413a04b4
Revises: 
Create Date: 2024-06-16 11:44:15.059821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e7413a04b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('is_erc20', sa.Boolean(), nullable=False),
    sa.Column('erc20_version', sa.String(length=255), nullable=True),
    sa.Column('contract_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('WAITS_PROCESSING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'contract_address'),
    sa.UniqueConstraint('contract_address'),
    sa.UniqueConstraint('contract_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    # ### end Alembic commands ###
