"""enum

Revision ID: cdf73b1465d8
Revises: 19e7413a04b4
Create Date: 2024-06-16 11:46:02.140881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf73b1465d8'
down_revision: Union[str, None] = '19e7413a04b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_contract_name_key', 'contract', type_='unique')
    op.drop_column('contract', 'contract_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('contract_contract_name_key', 'contract', ['contract_name'])
    # ### end Alembic commands ###
